{{- if not .Values.global.aspecto.existingSecret}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.name }}-secret
  labels: {{ tpl ( toYaml .Values.global.metadata.labels | nindent 4) . }}
  annotations: {{ tpl ( toYaml .Values.global.metadata.annotations | trim | nindent 4 ) . }}
type: Opaque
data: 
  api-key: {{ required "A valid api token is required." .Values.global.aspecto.apiToken | b64enc | quote }} 
{{- end }}