apiVersion: v2
name: aspecto-io-opentelemetry-collector
version: '1.0'
home: https://aspecto.io
type: application
sources:
  - https://github.com/open-telemetry/opentelemetry-collector
  - https://github.com/open-telemetry/opentelemetry-collector-contrib
maintainers:
  - name: dave-aspecto
keywords:
- aspecto
- opentelemetry
- observability
- traces
- jaeger
- otel
- collector
- sampling
icon: https://github.com/aspecto-io/opentelemetry-helm-charts/raw/main/assets/aspecto-io.png