{{- $root := . -}}
{{- $globalMetadata := .Values.global.metadata -}}
{{- $globalSharedLabels := $globalMetadata.shared.labels -}}
{{- $globalObjectLabels := $globalMetadata.service.labels }}
{{- $globalSharedAnnotations := $globalMetadata.shared.annotations }}
{{- $globalObjectAnnotations := $globalMetadata.service.annotations }}
{{- $localMetadata := .Values.redis.metadata -}}
{{- $localData := .Values.redis -}}
{{- $localDataSpec := .Values.redis.specs -}}
{{- $localMetadata := .Values.redis.metadata -}}

{{- if and ($localData.enabled) (eq $localData.config.type "local") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $root.Values.global.name }}-redis
  labels: {{ tpl ( toYaml $globalSharedLabels | nindent 4) $ }}
  {{- if $globalObjectLabels }}{{ tpl ( toYaml $globalObjectLabels | nindent 4) . }}{{- end }}
  {{- if $localMetadata.labels }}{{ tpl (toYaml $localMetadata.labels | nindent 4) . }}{{- end }}
  annotations: {{- if $globalSharedAnnotations }}{{ tpl ( toYaml $globalSharedAnnotations | nindent 4) $ }}{{- end }}
  {{- if $globalObjectAnnotations }}{{ tpl ( toYaml $globalObjectAnnotations | nindent 4) . }}{{- end }}
  {{- if $localMetadata.annotations }}{{ tpl (toYaml $localMetadata.annotations | nindent 4) . }}{{- end }}

spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: {{ $localDataSpec.port }}
      targetPort: {{ $localDataSpec.port }}
{{- end }}
