{{- $root := . -}}
{{- $globalMetadata := .Values.global.metadata -}}
{{- $globalSharedLabels := $globalMetadata.shared.labels -}}
{{- $globalObjectLabels := $globalMetadata.virtualService.labels }}
{{- $globalSharedAnnotations := $globalMetadata.shared.annotations }}
{{- $globalObjectAnnotations := $globalMetadata.virtualService.annotations }}
{{- $localMetadata := .Values.sampling_collector.metadata -}}
{{- $localSharedAnnotations := $localMetadata.shared.annotations -}}
{{- $localObjectAnnotations := $localMetadata.virtualService.annotations -}}
{{- $localSharedLabels := $localMetadata.shared.labels -}}
{{- $localObjectLabels := $localMetadata.virtualService.labels -}}
{{- $localListenerIp := .Values.sampling_collector.specs.network.localListenerIp -}}
{{- if .Values.sampling_collector.specs.network.istio.enabled }}
{{- range .Values.sampling_collector.specs.network.istio }}

apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ $root.sampling_collector.specs.network.serviceName }}-{{ .name }}-vsvc
  labels: {{ tpl ( toYaml $globalSharedLabels | nindent 4) $ }}
{{- if $globalObjectLabels }}{{ tpl ( toYaml $globalObjectLabels | nindent 4) . }}{{- end }}
{{- if $localObjectLabels }}{{ toYaml $localObjectLabels | nindent 4 }}{{- end }}
{{- if $localObjectLabels }}{{ toYaml $localObjectLabels | nindent 4 }}{{- end }}
  annotations: {{ tpl ( toYaml $globalSharedAnnotations | nindent 4) $ }}
{{- if $globalObjectAnnotations }}{{ tpl ( toYaml $globalObjectAnnotations | nindent 4) . }}{{- end }}
{{- if $localSharedAnnotations }}{{ toYaml $localSharedAnnotations | nindent 4 }}{{- end }}
{{- if $localObjectAnnotations }}{{ toYaml $localObjectAnnotations | nindent 4 }}{{- end }}
spec:
  hosts:
  {{ toYaml .istio.istio.hostHeader | trim | indent 4 }}
  gateways:
  - grpc-{{ $root.namespace }}-gateway
  http:
  {{- range .ingress }}
    - match:
      - uri:
          prefix: {{ .uriPrefix }}
      route:
      - destination:
          host: {{ $root.sampling_collector.specs.network.serviceName }}
          port:
            number: {{ .destinationPort }}
  {{- end }}
{{- end }}
{{- end }}